### PR TITLE
added a simple span message to line 154

### PR DESCRIPTION
**Pull request by meydipro**
Hi John, today I decided to work on your Work samples 
this makes me happy to help together...

### CODE REVIEW

**Comment by John-6670** [comment]
Hi  Mahdi, thanks for taking the time to contribute to my project! I appreciate your enthusiasm.
I'm not very familiar with frontend development, so I'd love to get a better understanding of how these changes might impact the website's look and feel.

**Comment by meydipro** [comment]
> Hi Mahdi, thanks for taking the time to contribute to my project! I appreciate your enthusiasm. I'm not very familiar with frontend development, so I'd love to get a better understanding of how these changes might impact the website's look and feel.

actually nothing 😅
I just tried to change something to measure communication on GIT skills.

**Comment by John-6670** [comment]
> > Hi Mahdi, thanks for taking the time to contribute to my project! I appreciate your enthusiasm. I'm not very familiar with frontend development, so I'd love to get a better understanding of how these changes might impact the website's look and feel.
> 
> actually nothing 😅
> I just tried to change something to measure communication on GIT skills.

Oh, I see. That's a great practice to do. Do you have skills on front-end projects?

**Comment by meydipro** [comment]
> Oh, I see. That's a great practice to do. Do you have skills on front-end projects?

can be said!

**Pull request closed without merging**
